length = float(input("Enter the length: "))
height = float(input("Enter the height: "))
breadth = float(input("Enter the breadth: "))
area = (length * breadth) + (length * height)
print(f"Output of {length} , {height} and {breadth} is {int(area)}")